# Document:
# http://simiki.org/docs/configuration.html

url: https://kafka-learn.github.io/kafka-code/
title: Kafka源码解析
keywords: Kafka源码解析 
description: Kafka源码解析
author: 余昕宇

root: /kafka-code/
source: content
destination: output
themes_dir: themes
theme: simple2

# category:
#   - name: linux  # the category directory name
#     label: Linux/运维  # alias name of category, used in index page
#   - name: database
#     label: 数据库

deploy:
  - type: git
    remote: https://github.com/kafka-learn/kafka-code
    branch: gh-pages  

default_ext: md
pygments: true
debug: false
